version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    
    - sphinx-apidoc -f -o docs/source/ lrnnx/ lrnnx/*/tests*
    
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt